### ISSUE TITLE
How to load data?

### ISSUE THREAD

**Issue by zhdanov** [GooGee/OpenAPI-Builder#16]
Dear GooGee,

Thank you for awesome tool!

But... How to load data? I try create file (data.json) and run serve.

**Comment by zhdanov** [comment]
Where is storage data? I search in cookies, local storage, html...

**Comment by GooGee** [comment]
I'm still working on it, sorry.

**Comment by zhdanov** [comment]
Loading in the develop branch is well (src/assets/preset.json). For the main branch I use public/data.json. It works for me.

For the export JSON I use this:
```
--- a/src/view/Home.vue
+++ b/src/view/Home.vue
@@ -52,6 +52,7 @@ export default defineComponent({
             })
         }
         function toJSON() {
+            console.log(JSON.stringify(ss.project));
             store.inputModal.text = JSON.stringify(ss.project.toOAPI())
             store.inputModal.show('OpenAPI JSON', () => {})
         }

```

**Comment by zhdanov** [comment]
But the main branch have a bug (#17)
