### ISSUE TITLE
Can't create path operation

### ISSUE THREAD

**Issue by zhdanov** [GooGee/OpenAPI-Builder#17]
![Peek 2021-11-14 16-44](https://user-images.githubusercontent.com/924980/141683846-067ad82e-c7b5-4705-b250-423af2528cbc.gif)

**Comment by zhdanov** [comment]
If you fix this bug, I'll try make the feature: Require-status for operation's parameters.

Also you can tell me how fix this bug. I know the place in the code (src/view/button/AddButton.vue:32) but I dont' understand what I should to do.

**Comment by GooGee** [comment]
Thank you very much, I'll deal with it soon.

**Comment by zhdanov** [comment]
Fixed! :tada:
